<?php
/**
 * Created by PhpStorm.
 * User: liwenling
 * Date: 2018/5/23
 * Time: 下午4:40
 */

namespace frontend\controllers;

use Yii;
use yii\log;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\Airticle;

/**
 * Site controller
 */
class WldfController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->layout = false;
        $this->enableCsrfValidation = false;
    }

    public function actionT(){

        $res = array('aaa','bbb');

        return json_encode($res);
    }

    public function actionBooks(){
//        phpinfo();
        $id = 1;
        $r = Airticle::getById($id);
        var_dump($r->attributes);exit;
        return  $r;


    }

    /**
     * 文章详情
     * @return string
     */
    public function actionDetail(){
        $bid = Yii::$app->request->get('bid');
        $sn = Yii::$app->request->get('sn');

        $detail  = Airticle::getDetail($bid, $sn);

        $data = ['detail' => $detail->attributes];
        return $this->render('detail', $data);
    }

    public function actionMyRead()
    {
        $uid = Yii::$app->request->get('uid');
        $bid = Yii::$app->request->get('bid');

        $my_log = Airticle::getMylog($uid, $bid);
        $mylog = empty($my_log) ? 1 : $my_log->sn;

        $detail  = Airticle::getDetail($bid, $mylog);
        $data = ['detail' => $detail->attributes];
        return $this->render('mylog', $data);
    }

    public function actionDoRead()
    {
        $uid = Yii::$app->request->post('uid');
        $bid = Yii::$app->request->post('bid');
        $sn = Yii::$app->request->post('sn');

        $detail  = Airticle::getDetail($bid, $sn);
        $r = Airticle::updateMylog($uid, $bid, $sn);

        return json_encode($detail->attributes);
    }

}